routeEnhancers:
  BlogSystem:
    type: Extbase
    extension: BlogSystem
    plugin: BlogList
    routes:
      - routePath: '/'
        _controller: 'Blog::list'
      - routePath: '/{blog_title}'
        _controller: 'Blog::show'
        _arguments:
          blog_title: blog
    aspects:
      blog_title:
        type: PersistedAliasMapper
        tableName: tx_blogsystem_domain_model_blog
        routeFieldName: path_segment
        fallbackValue: '0'